version: "3.9"

services:
  web:
    container_name: timewarp-frontend-dev
    image: timewarp-frontend-dev
    build:
      context: .
      target: dev
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - 9876:80
    restart: always
