export enum PuzzleIds {
	TUTORIAL_PUZZLE = 0,
	MORSE_AUDIO_PUZZLE = 1,
	STEGANOGRAPHY = 2,
	MST_PUZZLE = 3,
	SOUND_PUZZLE = 4,
	EMOJI_PUZZLE = 5,
	INTERCEPT_PUZZLE = 6,
	REV_ENG_PUZZLE = 7,
	TRAPS_PUZZLE = 8,
}
